### ISSUE TITLE
MCPサーバーのデプロイ設定実装

### ISSUE THREAD

**Issue by ryosuke-horie** [ryosuke-horie/effective-yomimono#100]
## 概要
基本的なMCPサーバーのデプロイ設定を実装し、Cloudflare Workersへの展開を可能にします。

### デプロイ設定
1. Wrangler設定の更新
2. 環境変数の設定
3. デプロイスクリプトの作成

### セキュリティ設定
- APIキー管理
- CORS設定
- レート制限

## タスク
- [ ] Wrangler設定の更新
  - [ ] MCPサーバー用の設定追加
  - [ ] 環境変数の設定
  - [ ] ルーティング設定の更新

- [ ] デプロイスクリプトの実装
  - [ ] デプロイワークフローの作成
  - [ ] ロールバック手順の作成
  - [ ] ヘルスチェックの実装

- [ ] セキュリティ設定
  - [ ] APIキー管理の実装
  - [ ] CORS設定の実装
  - [ ] レート制限の設定

- [ ] 監視設定
  - [ ] ログ設定
  - [ ] アラート設定
  - [ ] メトリクス収集設定

## 設定例
```toml
# wrangler.toml
name = "effective-yomimono-mcp"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
MCP_SERVER_NAME = "YomimonoMCPServer"
MCP_SERVER_DESCRIPTION = "技術記事ブックマークを管理するための MCP サーバー"

# 環境変数
[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }
```

## デプロイフロー
1. ステージング環境へのデプロイ
2. テストの実行
3. 本番環境へのデプロイ
4. ヘルスチェック
5. ロールバック手順（必要な場合）

## 期待される結果
- MCPサーバーが Cloudflare Workers で安定して動作する
- セキュアなアクセス制御が実装されている
- 監視とアラートが適切に設定されている
- デプロイプロセスが自動化されている

## 関連ドキュメント
- [implementation_guide.md](./docs/mcp/implementation_guide.md)
- [sample_implementation.md](./docs/mcp/sample_implementation.md)
