### ISSUE TITLE
RSS読み込み機能 - 10. デプロイ設定と本番環境準備

### ISSUE THREAD

**Issue by ryosuke-horie** [ryosuke-horie/effective-yomimono#388]
## 概要
RSS読み込み機能を本番環境にデプロイするための設定を行い、運用開始の準備をする。

## 実装内容
- [ ] Wranglerの設定ファイル更新
- [ ] 環境変数の設定
- [ ] Cron Triggerの本番設定
- [ ] デプロイスクリプトの作成
- [ ] 運用ドキュメントの作成

### Wrangler設定
```toml
# wrangler.toml
name = "effective-yomimono-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "effective-yomimono-api-production"
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "effective-yomimono"
database_id = "xxxxx-xxxxx-xxxxx"

[triggers]
crons = ["0 0 * * *"] # 毎日深夜0時に実行

[[kv_namespaces]]
binding = "CACHE"
id = "xxxxx-xxxxx-xxxxx"
```

### GitHub Actions設定
```yaml
# .github/workflows/deploy-rss.yml
name: Deploy RSS Feature

on:
  push:
    branches:
      - main
    paths:
      - 'api/src/**'
      - 'frontend/src/**'
      - 'wrangler.toml'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd api
          npm ci
          
      - name: Run tests
        run: |
          cd api
          npm test
          
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: api
          command: deploy --env production
          
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          
      - name: Build
        run: |
          cd frontend
          npm run build
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=effective-yomimono
```

### 環境変数設定
```bash
# .env.production
DATABASE_URL=xxxxx
API_TOKEN=xxxxx
CLOUDFLARE_ACCOUNT_ID=xxxxx
CLOUDFLARE_API_TOKEN=xxxxx
```

### デプロイ手順書
```markdown
# RSS機能デプロイ手順

## 前提条件
- Cloudflareアカウントの準備
- D1データベースの作成
- KVネームスペースの作成

## 手順

1. データベースマイグレーション
   ```bash
   cd api
   npm run migrate:production
   ```

2. API デプロイ
   ```bash
   cd api
   wrangler deploy --env production
   ```

3. フロントエンドデプロイ
   ```bash
   cd frontend
   npm run build
   wrangler pages deploy dist
   ```

4. Cron Triggerの確認
   - Cloudflareダッシュボードで確認
   - 実行ログの監視

5. 動作確認
   - フィード登録テスト
   - 手動実行テスト
   - 自動実行の確認（翌日）
```

### 運用監視設定
```typescript
// api/src/monitoring/rss.ts
export class RSSMonitoring {
  async checkHealth(): Promise<HealthStatus> {
    const checks = await Promise.all([
      this.checkDatabase(),
      this.checkLastBatchRun(),
      this.checkErrorRate(),
    ]);
    
    return {
      status: checks.every(c => c.ok) ? 'healthy' : 'degraded',
      checks,
      timestamp: new Date(),
    };
  }
  
  private async checkDatabase(): Promise<Check>
  private async checkLastBatchRun(): Promise<Check>
  private async checkErrorRate(): Promise<Check>
}
```

## 作業内容
1. Wrangler設定ファイルの更新
2. GitHub Actions ワークフローの作成
3. 環境変数の設定
4. デプロイ手順書の作成
5. 監視設定の実装
6. 本番環境でのテスト実行

## 受け入れ条件
- [ ] 本番環境にデプロイできること
- [ ] Cron Triggerが正常に動作すること
- [ ] 監視が機能していること
- [ ] ロールバックが可能であること
- [ ] 運用ドキュメントが完成していること

## 依存関係
- Issue #378〜#387 の完了が必要

## ブランチ名
`deploy/issue-XXX-rss-production`
