### ISSUE TITLE
記事評価ポイント機能: 包括的テスト・品質保証

### ISSUE THREAD

**Issue by ryosuke-horie** [ryosuke-horie/effective-yomimono#543]
## 概要
記事評価ポイント機能の包括的なテスト実装と品質保証を行う。ユニットテスト、統合テスト、E2Eテスト、パフォーマンステストを含む。

## 背景
全実装フェーズ完了後の品質保証として、信頼性の高いテストスイートを構築し、本番デプロイの準備を整える。

### テスト範囲
- [ ] ユニットテスト (85%以上のカバレッジ)
- [ ] 統合テスト (API↔DB, MCP↔API)
- [ ] E2Eテスト (UI操作、ワークフロー)
- [ ] パフォーマンステスト
- [ ] セキュリティテスト

### 品質保証項目
- [ ] コードレビュー・リファクタリング
- [ ] ドキュメント更新
- [ ] CI/CD パイプライン整備
- [ ] 本番デプロイ準備

#### Database Layer
```typescript
// api/src/repositories/articleRating.test.ts
describe('ArticleRatingRepository', () => {
  test('評価作成の正常系', async () => {
    const rating = await articleRatingRepo.create({
      articleId: 1,
      practicalValue: 8,
      technicalDepth: 7,
      understanding: 9,
      novelty: 6,
      importance: 8
    });
    
    expect(rating.totalScore).toBe(7.6);
    expect(rating.articleId).toBe(1);
  });
  
  test('重複評価の異常系', async () => {
    await articleRatingRepo.create(sampleRating);
    
    await expect(
      articleRatingRepo.create(sampleRating)
    ).rejects.toThrow('Rating already exists');
  });
  
  test('評価値範囲外の異常系', async () => {
    const invalidRating = { ...sampleRating, practicalValue: 11 };
    
    await expect(
      articleRatingRepo.create(invalidRating)
    ).rejects.toThrow('Score out of range');
  });
});
```

#### Service Layer
```typescript
// api/src/services/rating.test.ts
describe('RatingService', () => {
  test('評価統計情報の計算', async () => {
    await setupTestRatings();
    
    const stats = await ratingService.getStats();
    
    expect(stats.totalRatings).toBe(10);
    expect(stats.averageScore).toBeCloseTo(7.5, 1);
    expect(stats.dimensionAverages.practicalValue).toBeCloseTo(8.0, 1);
  });
  
  test('評価フィルター機能', async () => {
    const ratings = await ratingService.getRatings({
      minScore: 8.0,
      maxScore: 10.0,
      sortBy: 'totalScore',
      order: 'desc'
    });
    
    expect(ratings.every(r => r.totalScore >= 8.0)).toBe(true);
    expect(ratings[0].totalScore).toBeGreaterThanOrEqual(ratings[1].totalScore);
  });
});
```

#### MCP Layer
```typescript
// mcp/src/test/mcpTools.test.ts
describe('MCP Rating Tools', () => {
  test('rateArticle ツールの正常動作', async () => {
    const result = await mcpServer.callTool('rateArticle', {
      articleId: 1,
      practicalValue: 8,
      technicalDepth: 7,
      understanding: 9,
      novelty: 6,
      importance: 8,
      comment: 'テストコメント'
    });
    
    expect(result.isError).toBe(false);
    expect(result.content[0].text).toContain('総合スコア: 7.6/10');
  });
  
  test('記事内容取得の統合テスト', async () => {
    const mockUrl = 'https://example.com/test-article';
    mockPlaywrightMcp(mockUrl, mockArticleContent);
    
    const result = await mcpServer.callTool('rateArticleWithContent', {
      articleId: 1,
      url: mockUrl,
      fetchContent: true
    });
    
    expect(result.isError).toBe(false);
    expect(result.content[0].text).toContain('記事内容取得完了');
  });
});
```

### 2. 統合テスト
```typescript
// tests/integration/ratingWorkflow.test.ts
describe('記事評価ワークフロー統合テスト', () => {
  test('記事作成→評価→取得の完全フロー', async () => {
    // 1. 記事作成
    const article = await request(app)
      .post('/api/bookmarks')
      .send({
        title: 'テスト記事',
        url: 'https://example.com/test'
      })
      .expect(201);
    
    // 2. 評価作成
    const rating = await request(app)
      .post(`/api/bookmarks/${article.body.bookmark.id}/rating`)
      .send({
        practicalValue: 8,
        technicalDepth: 7,
        understanding: 9,
        novelty: 6,
        importance: 8,
        comment: '統合テスト'
      })
      .expect(201);
    
    // 3. 評価取得
    const retrieved = await request(app)
      .get(`/api/bookmarks/${article.body.bookmark.id}/rating`)
      .expect(200);
    
    expect(retrieved.body.rating.totalScore).toBe(7.6);
    expect(retrieved.body.rating.comment).toBe('統合テスト');
  });
  
  test('MCP ↔ API 連携テスト', async () => {
    // MCPツール経由での評価作成
    const mcpResult = await mcpClient.callTool('rateArticle', testRating);
    expect(mcpResult.isError).toBe(false);
    
    // API経由での確認
    const apiResult = await request(app)
      .get(`/api/bookmarks/${testRating.articleId}/rating`)
      .expect(200);
    
    expect(apiResult.body.rating.practicalValue).toBe(testRating.practicalValue);
  });
});
```

### 3. E2Eテスト
```typescript
// tests/e2e/ratingPages.test.ts
describe('評価ページ E2E テスト', () => {
  test('評価一覧ページの表示と操作', async ({ page }) => {
    await page.goto('/ratings');
    
    // 統計情報の表示確認
    await expect(page.locator('.stats-summary')).toBeVisible();
    await expect(page.locator('.stat-value').first()).toContainText(/\d+/);
    
    // フィルター操作
    await page.selectOption('select[name="sortBy"]', 'totalScore');
    await page.check('input[name="hasComment"]');
    
    // 結果の確認
    const ratingItems = page.locator('.rating-item');
    await expect(ratingItems.first()).toBeVisible();
    
    // スコア降順の確認
    const scores = await ratingItems.locator('.score-text').allTextContents();
    const numericScores = scores.map(s => parseFloat(s));
    expect(numericScores).toEqual([...numericScores].sort((a, b) => b - a));
  });
  
  test('レスポンシブ対応の確認', async ({ page }) => {
    // モバイル表示
    await page.setViewportSize({ width: 375, height: 667 });
    await page.goto('/ratings');
    
    await expect(page.locator('.rating-filters')).toBeVisible();
    await expect(page.locator('.ratings-list')).toBeVisible();
    
    // タブレット表示
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.reload();
    
    await expect(page.locator('.stats-summary')).toBeVisible();
  });
});
```

### 4. パフォーマンステスト
```typescript
// tests/performance/ratingPerformance.test.ts
describe('パフォーマンステスト', () => {
  test('大量データでの評価一覧取得', async () => {
    // 1000件の評価データを作成
    await createTestRatings(1000);
    
    const startTime = Date.now();
    const response = await request(app)
      .get('/api/ratings?limit=100')
      .expect(200);
    const endTime = Date.now();
    
    // 1秒以内の応答時間
    expect(endTime - startTime).toBeLessThan(1000);
    expect(response.body.ratings).toHaveLength(100);
  });
  
  test('統計情報計算のパフォーマンス', async () => {
    await createTestRatings(5000);
    
    const startTime = Date.now();
    const stats = await ratingService.getStats();
    const endTime = Date.now();
    
    // 2秒以内の計算時間
    expect(endTime - startTime).toBeLessThan(2000);
    expect(stats.totalRatings).toBe(5000);
  });
  
  test('並行評価作成のストレステスト', async () => {
    const concurrentRequests = Array.from({ length: 50 }, (_, i) => 
      request(app)
        .post(`/api/bookmarks/${i + 1}/rating`)
        .send(generateRandomRating())
    );
    
    const results = await Promise.allSettled(concurrentRequests);
    const successful = results.filter(r => r.status === 'fulfilled').length;
    
    // 90%以上の成功率
    expect(successful / concurrentRequests.length).toBeGreaterThan(0.9);
  });
});
```

### 5. セキュリティテスト
```typescript
// tests/security/ratingSecurity.test.ts
describe('セキュリティテスト', () => {
  test('SQLインジェクション対策', async () => {
    const maliciousInput = "1; DROP TABLE article_ratings; --";
    
    const response = await request(app)
      .get(`/api/ratings?sortBy=${maliciousInput}`)
      .expect(400);
    
    expect(response.body.message).toContain('Invalid sortBy value');
  });
  
  test('XSS対策 - コメント入力', async () => {
    const xssPayload = '<script>alert("xss")</script>';
    
    const response = await request(app)
      .post('/api/bookmarks/1/rating')
      .send({
        ...validRating,
        comment: xssPayload
      })
      .expect(201);
    
    // HTMLエスケープされているか確認
    expect(response.body.rating.comment).not.toContain('<script>');
  });
  
  test('入力値範囲チェック', async () => {
    const invalidRating = {
      ...validRating,
      practicalValue: 15,  // 範囲外
      technicalDepth: -1   // 範囲外
    };
    
    await request(app)
      .post('/api/bookmarks/1/rating')
      .send(invalidRating)
      .expect(422);
  });
});
```

### 6. CI/CD パイプライン強化
```yaml
# .github/workflows/rating-feature-tests.yml
name: 記事評価機能テスト

on:
  push:
    paths:
      - 'api/src/**/*rating*'
      - 'mcp/src/**'
      - 'frontend/src/features/ratings/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run API Unit Tests
        run: |
          cd api
          npm ci
          npm run test:unit -- --coverage
      - name: Run MCP Unit Tests  
        run: |
          cd mcp
          npm ci
          npm test
  
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Integration Tests
        run: |
          cd api
          npm run test:integration
          
  e2e-tests:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E Tests
        run: |
          cd frontend
          npm ci
          npm run test:e2e
          
  performance-tests:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Run Performance Tests
        run: |
          cd api
          npm run test:performance
```

## 完了条件
- [ ] ユニットテスト: 85%以上のカバレッジ
- [ ] 統合テスト: 主要ワークフロー網羅
- [ ] E2Eテスト: UI操作・レスポンシブ対応
- [ ] パフォーマンステスト: 要件クリア
- [ ] セキュリティテスト: 主要脆弱性対策
- [ ] CI/CD パイプライン更新
- [ ] ドキュメント更新
- [ ] 本番デプロイ準備完了

## 品質指標
- [ ] API応答時間: 95%のリクエストが200ms以内
- [ ] テストカバレッジ: 85%以上
- [ ] E2Eテスト成功率: 100%
- [ ] パフォーマンステスト: 全項目クリア
- [ ] セキュリティスキャン: 重大な脆弱性0件

## 参考資料
- [07_実装計画.md](../docs/機能仕様/記事評価ポイント機能/07_実装計画.md)
- [品質指標定義](../docs/機能仕様/記事評価ポイント機能/07_実装計画.md#5-成功指標-kpi)

## 依存関係
- **前提**: 全実装フェーズ (#536-#542) 完了
- **完了後**: 本番デプロイ・リリース

## 実装期間
- 見積もり: 6-7日
- 締切: 全体開発完了

---
📝 **最終フェーズ** - 包括的テスト・品質保証
🔗 関連: MCP記事評価機能
🎯 目標: 本番デプロイ可能な品質確保
