### ISSUE TITLE
MCPテストをセルフホストランナーで実行するCI構築

### ISSUE THREAD

**Issue by ryosuke-horie** [ryosuke-horie/effective-yomimono#572]
## 概要
MCPのテストコードをPRの更新時に限定してセルフホストランナーで実行するCIワークフローを構築する。

## 背景
現在のMCPテストは通常のGitHub-hostedランナーで実行されているが、以下の理由でセルフホストランナーでの実行が必要：
- MCPテストの特殊性（ブラウザ自動化、Playwright等）
- リソース制約の回避
- 実行環境の一貫性確保
- 長時間実行テストの対応

### 機能要件
- [ ] PRの作成・更新時のみMCPテストを実行
- [ ] セルフホストランナーでのテスト実行
- [ ] 他のCIジョブ（lint、typecheck等）は既存のGitHub-hostedランナーで継続
- [ ] MCPディレクトリの変更検知による条件実行
- [ ] テスト結果のPRへのフィードバック

### 技術要件
- [ ] `.github/workflows/mcp-test-selfhosted.yml` の作成
- [ ] セルフホストランナーのラベル指定
- [ ] paths フィルターによるMCPディレクトリ変更検知
- [ ] 既存のMCPテストワークフローとの統合・置き換え
- [ ] 並列実行の制御

### 1. ワークフローファイル構成
```yaml
name: MCP Tests (Self-hosted)

on:
  pull_request:
    paths:
      - 'mcp/**'
    types: [opened, synchronize, reopened]

jobs:
  mcp-tests:
    runs-on: [self-hosted, linux, mcp]
    defaults:
      run:
        working-directory: mcp
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: mcp/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm run test
      
      - name: Run coverage
        run: npm run test:coverage
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: mcp/coverage
```

### 2. セルフホストランナー設定
- **ランナーラベル**: `[self-hosted, linux, mcp]`
- **必要な環境**: Node.js 18+, npm, Playwright dependencies
- **リソース要件**: メモリ4GB以上、ディスク容量20GB以上

### 3. 既存ワークフローとの関係
- 既存の `mcp-lint.yml` は継続（GitHub-hostedランナー）
- MCPテスト部分のみセルフホストランナーに移行
- 他のプロジェクト（api, frontend）は既存の設定を維持

### 4. 条件実行の詳細設定
```yaml
# MCPディレクトリの変更時のみ実行
on:
  pull_request:
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-test-selfhosted.yml'
    types: [opened, synchronize, reopened]

# mainブランチへのプッシュ時は除外
  push:
    branches-ignore:
      - main
```

## 完了条件
- [ ] セルフホストランナーでのMCPテスト実行ワークフローの作成
- [ ] PRの更新時のみ実行される条件設定
- [ ] MCPディレクトリ変更検知の動作確認
- [ ] テスト結果のPRステータス反映
- [ ] 既存ワークフローとの競合回避
- [ ] セルフホストランナーの動作確認
- [ ] ドキュメント更新（README、運用手順）

## 影響範囲
- **CI/CD**: 新しいワークフローの追加
- **開発フロー**: PRでのMCPテスト実行方法の変更
- **インフラ**: セルフホストランナーの設定・運用

## 参考資料
- [GitHub Actions self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners)
- [Workflow path filtering](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
- [PR-only workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)

## 実装期間
- 見積もり: 1-2日
- 優先度: Medium

---
📝 **重要度: MEDIUM** - MCPテスト実行環境の最適化
🔗 関連: CI/CD改善、テスト実行環境
🎯 目標: PRでのMCPテスト実行の効率化と信頼性向上
